project:
  type: book

book:
  title: "data-literacy-and-proficiency"
  author: "Norah Jones"
  date: "18.3.2026"
  chapters:
    - index.qmd
    - 01_welcome.qmd
    - 02_modularization.qmd
    - 03_introduction.qmd
    - 05_statistics.qmd
    - intro.qmd
    - visualization.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  live-html:
    theme:
      - cosmo
      - brand
    css: webex.css
    include-after-body: webex.js

engine: knitr


